name: wan_android_backend

description: Wan Android Backend Server.

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  shelf_router: ^1.1.4
#  args: ^2.4.0
  shelf: ^1.4.2
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
