name: wan_android
description: "玩安卓Flutter版本。"
publish_to: 'none'

version: 1.0.0+100

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.1
  logger: ^2.3.0
  easy_refresh: ^3.4.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.6
  cached_network_image: ^3.3.1
  dio: ^5.5.0
  pretty_dio_logger: ^1.3.1
  animations: ^2.0.11
  path_drawing: ^1.0.1
  convert: ^3.1.1
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  cookie_jar: ^4.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_inappwebview: ^6.0.0

dev_dependencies:

  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  image_path_android: "assets/icons/launcher_icon.png"
  image_path_ios: "assets/icons/launcher_icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.png"


