name: wan_android_backend

description: Wan Android Backend Server.

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  shelf_router: ^1.1.4
  shelf_proxy: ^1.0.4
  shelf: ^1.4.1
  http: ^1.2.2
  hive: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  shelf_router_generator: ^1.1.0
  build_runner: ^2.4.11
