name: Deploy wanAndroid web

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build wanAndroid web
    runs-on: ubuntu-latest

    env:
      # 使用Github自动生成的令牌
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get
        working-directory: wan_android_flutter

      - name: Start web release build
        run: flutter build web --release
        working-directory: wan_android_flutter

      - name: Upload web build files
        uses: actions/upload-artifact@v2
        with:
          name: web-release
          path: ./wan_android_flutter/build/web

  deploy:
    name: Deploy wanAndroid web
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download web release
        uses: actions/download-artifact@v2
        with:
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
